// <auto-generated />
namespace GameLibrary.Models.ContextNamespace2
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class Context2Init : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Context2Init));
        
        string IMigrationMetadata.Id
        {
            get { return "201404160039109_Context2Init"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
